# Generated by Django 4.0.5 on 2022-06-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title1',
            new_name='title',
        ),
    ]
