# Generated by Django 4.0.5 on 2022-07-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_tag_articletag_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
