# Generated by Django 4.0.5 on 2022-07-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_tags_article_tags_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='old_articles', through='webapp.ArticleTag', to='webapp.tag'),
        ),
    ]
